on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  fetch-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: |
          chmod +x fetch_latest.sh

      - run: |
          ./fetch_latest.sh
